name: mrf-subspace
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyter
  - matplotlib
  - numpy=1.22
  - python=3.10
  - pytorch>=2.0
  - pytorch-cuda
  - scipy
  - torchvision
  - tqdm
  - pytest
  - pyyaml
  - pip
  - pip:
     - easydict
     - einops
     - gdown
     - h5py
     - mat73 # loading matlab v7.3 format files
     - pytorch_memlab
     - pyyaml
     - sigpy==0.1.25
     - torchkbnufft==1.4.0
     - tyro
     - wget
